apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: enterprise-contract
  name: enterprise-contract
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: enterprise-contract
  labels:
    name: enterprise-contract-controller
spec:
  selector:
    matchLabels:
      name: enterprise-contract-controller
  replicas: 1
  template:
    metadata:
      labels:
        name: enterprise-contract-controller
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: enterprise-contract-controller
        image: ko://github.com/enterprise-contract/enterprise-contract-controller
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi

      serviceAccountName: enterprise-contract-controller
      terminationGracePeriodSeconds: 10
