# permissions for end users to edit enterprisecontractpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enterprisecontractpolicy-editor-role
  labels:
    # Bind this role to users already bound to the "edit" ClusterRole.
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - enterprisecontractpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - enterprisecontractpolicies/status
  verbs:
  - get
