# permissions for end users to view enterprisecontractpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enterprisecontractpolicy-viewer-role
  labels:
    # Bind this role to users already bound to the "view" ClusterRole.
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - enterprisecontractpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - enterprisecontractpolicies/status
  verbs:
  - get
