apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  creationTimestamp: null
  name: ec-policy
  namespace: acme
spec:
  configuration:
    exclude:
    - friday_policy
    - room_temperature
  description: ACME & co policy
  sources:
  - git::https://github.com/acme/ec-policy.git//policy?ref=prod
status: {}
