apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  creationTimestamp: null
  name: ec-policy
  namespace: acme
spec:
  description: ACME & co policy
  exceptions:
    nonBlocking:
    - friday_policy
    - room_temperature
  sources:
  - git:
      repository: https://github.com/acme/ec-policy.git
      revision: production
status: {}
