apiVersion: console.openshift.io/v1
kind: ConsoleYAMLSample
metadata:
  name: ecp-example
spec:
  targetResource:
    apiVersion: appstudio.redhat.com/v1alpha1
    kind: EnterpriseContractPolicy
  title: Example Enterprise Contract Policy
  description: Example of custom Enterprise Contract Policy
  yaml: |
    apiVersion: appstudio.redhat.com/v1alpha1
    kind: EnterpriseContractPolicy
    metadata:
      name: acme-policy
    spec:
      description: ACME Enterprise Contract Policy configuration
      configuration:
        include:
          - "@slsa1"
          - "@slsa2"
          - "@acme"
      publicKey: k8s://openshift-pipelines/public-key
      sources:
        - name: Default EC Policies
          data:
            - git::https://github.com/conforma/policy//example/data
          policy:
            - oci::quay.io/hacbs-contract/ec-release-policy:latest
          ruleData:
            allowed_registry_prefixes:
            - registry.access.redhat.com/
            - registry.redhat.io/
            - registry.io/acme/
        - name: ACME Policies
          policy:
            - oci::registry.io/acme/enterprise-rules:latest
