apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# get the base config under config/default
resources:
  - ../../default

patches:
  - path: enable-reconciler-patch.yaml
    target:
      kind: Deployment
      name: enterprise-contract-controller